[default]

dynaconf_env = "DEFAULT"
fastapi_title = "PID Monitoring and Resolution"
fastapi_description = "Rest API to register PIDMR resolution events."
fastapi_version = "0.1.0"
fastapi_summary = ""
loggers = [{ "name" = "prm", "log_file" = "@format {env[BASE_DIR]}/logs/prm.log", "log_level" = 20, "log_format" = "%(asctime)s - %(name)s - %(levelname)s - %(message)s", "log_date_format" = "%Y-%m-%d %H:%M:%S" }, { "name" = "pidmr", "log_file" = "@format {env[BASE_DIR]}/logs/pidmr.log", "log_level" = 20, "log_format" = "%(asctime)s - %(name)s - %(levelname)s - %(message)s", "log_date_format" = "%Y-%m-%d %H:%M:%S" }]

pyproject_toml_path = '../pyproject.toml'
pidresolver_email = "stein.steiny@gmail.com"
pidresolver_max_redir = 20
pidresolver_user_agent = "@format {this.fastapi_title}/{this.fastapi_version} (mailto:{this.pidresolver_email})"

pidresolver_timeout = 30
pidresolver_read_timeout = 60

celery_max_group_size = 8

jwt_token_expire_days = 365

[development]
dynaconf_env = "DEVELOPMENT"

[staging]
dynaconf_env = "STAGING"

[testing]
dynaconf_env = "TESTING"

[production]
dynaconf_env = "PRODUCTION"
