[default]
dynaconf_env = "DEFAULT"
fastapi_title = "PID Resolution Monitor"
fastapi_description = "Rest API to register PIDMR resolution events."
fastapi_version = "0.1.0"
fastapi_summary = ""
loggers = [{ "name" = "prm", "log_file" = "../../logs/prm.log", "log_level" = 10, "log_format" = "%(asctime)s %(levelname)s: %(message)s", "log_date_format" = "%Y-%m-%d %H:%M:%S" }]
#log_file = "@format {env[BASE_DIR]}/logs/prm.log"
max_celery_group_size = 5

[development]
dynaconf_env = "DEVELOPMENT"

[staging]
dynaconf_env = "STAGING"

[testing]
dynaconf_env = "TESTING"

[production]
dynaconf_env = "PRODUCTION"
